# .github/workflows/sync.yml
name: Sync Fork

on:
  schedule:
    - cron: '30 05 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.TOKEN }} # sostituisci con il tuo token

      - name: Pull changes
        run: |
          git pull
